DROP TABLE students IF EXISTS;
DROP TABLE supervisors IF EXISTS;
DROP TABLE notices IF EXISTS;
DROP TABLE notice_receiver IF EXISTS;
DROP TABLE project_proposals IF EXISTS;

CREATE TABLE students (
  student_id INTEGER,
  user_name VARCHAR(30),
  student_email VARCHAR(30),
  student_department VARCHAR(30),
  supervisor_id INTEGER,
  cell_phone_number VARCHAR(30),
  password VARCHAR(20)
);

CREATE TABLE supervisors (
  supervisor_id INTEGER ,
  user_name VARCHAR(30),
  email VARCHAR(30),
  department VARCHAR(30)
);

CREATE TABLE notices (
  notice_id INTEGER ,
  publisher_id INTEGER,
  receiver_string VARCHAR(30),
  publish_time BIGINT,
  subject  VARCHAR(200),
  description VARCHAR(530)
);

CREATE TABLE notice_receiver(
  notice_id INTEGER ,
  receiver_id INTEGER
);

CREATE TABLE project_proposals (
  tbl_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  student_id INTEGER,
  supervisor_id INTEGER,
  is_confirmed INTEGER,
  first_sent_time BIGINT,
  last_sent_time BIGINT,
  revisions INTEGER,
  supervisor_comment VARCHAR(200),
  project_title VARCHAR(100),
  project_for VARCHAR(100),
  project_doing_at VARCHAR(50),
  objective VARCHAR(200),
  technological_stacks VARCHAR(500),
  modules VARCHAR(200),
  actors VARCHAR(100),
  functional_requirements VARCHAR(1000)
);